name: app_store_apple_store
description: Apple App Store implementation
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  in_app_review: 2.0.11

  app_store_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  openfoodfacts_flutter_lints:
    git: https://github.com/openfoodfacts/openfoodfacts_flutter_lints.git